VERSION = "2.0"
NAME = "Python cmd"
LICENSE = "MIT License 2024 CodeCrafter Studio"
COLON = ": "
CMD_NOT_DEFINED = "未知命令"
CMD_NOT_FOUND = "已知但无逻辑的命令"
MISS_ARG = "缺失参数"
NEED_ARG = "需要参数"
LARGE_ARG = "参数过多"
FILE_NOT_FOUND = "未找到文件"
DIR_NOT_FOUND = "未找到目录"
CONFIG_KEY_NOT_FOUND = "未知的配置键值"
INVALID_CONFIG_KEY = "无效的配置键值"
INVALID_CONFIG_VALUE = "无效的配置值"
READONLY_FILE = "文件或目录是只读的"
NO_SUDO = "权限不足"
NEED_RESTART = "需要重新启动"
TIMEOUT = " 秒后继续"
PAUSE = "按任意键继续"
USET_ABORT = "被用户中断"
# 日志记录设置
logging_enabled: bool = True  # 默认开启日志记录
log_file_max_size: int = 10240  # 默认日志文件最大大小为10KB
log_file_max_age: int = 30  # 默认日志文件保留时间为30天
log_file_max_count: int = 10  # 默认日志文件保留数量为10