# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Download and extract UPX
      run: |
        New-Item -ItemType Directory -Path "D:\upx" -Force
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-win64.zip" -OutFile "D:\upx\upx.zip"
        Expand-Archive -Path "D:\upx\upx.zip" -DestinationPath "D:\upx" -Force
        Remove-Item "D:\upx\upx.zip"
        Write-Host "UPX:"
        Get-ChildItem "D:\upx" -Recurse | ForEach-Object { $_.FullName }
    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller Pillow
        pip install -r requirements.txt
        pyinstaller --onefile --windowed --icon=icons/logo.png --name "Huki-terminal" --add-data=icons/*:icons --upx-dir="D:/upx/upx-4.2.4-win64" --upx-exclude=python3.dll main.py;
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Huki-terminal
        path: ./dist/*
          
